"""empty message

Revision ID: 45298f5b11ff
Revises: bc0d3824847e
Create Date: 2019-05-01 00:39:05.338531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45298f5b11ff'
down_revision = 'bc0d3824847e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),    
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counter')
    # ### end Alembic commands ###
