"""empty message

Revision ID: bc0d3824847e
Revises: 45b947071e3b
Create Date: 2019-04-30 20:38:25.488209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0d3824847e'
down_revision = '45b947071e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('display', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'display')
    # ### end Alembic commands ###
